"""
AlphaForge Risk Engine Enumerations.
Defines decision states, deterministic reason codes, and trade sides.
"""

from enum import StrEnum


class RiskDecisionState(StrEnum):
    """Core outcome of a risk evaluation."""

    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    INVALID = "INVALID"


class RiskReasonCode(StrEnum):
    """
    Deterministic machine-readable codes explaining risk decisions.
    All failure cases map to an explicit non-generic code.
    """

    APPROVED = "APPROVED"
    INVALID_EQUITY = "INVALID_EQUITY"
    INVALID_ENTRY_PRICE = "INVALID_ENTRY_PRICE"
    INVALID_STOP_PRICE = "INVALID_STOP_PRICE"
    INVALID_STOP_DIRECTION = "INVALID_STOP_DIRECTION"
    INVALID_RISK_DISTANCE = "INVALID_RISK_DISTANCE"
    STOP_DISTANCE_TOO_SMALL = "STOP_DISTANCE_TOO_SMALL"
    STOP_DISTANCE_TOO_LARGE = "STOP_DISTANCE_TOO_LARGE"
    RISK_LIMIT_EXCEEDED = "RISK_LIMIT_EXCEEDED"
    PORTFOLIO_RISK_EXCEEDED = "PORTFOLIO_RISK_EXCEEDED"
    MAX_OPEN_TRADES_EXCEEDED = "MAX_OPEN_TRADES_EXCEEDED"
    POSITION_NOTIONAL_EXCEEDED = "POSITION_NOTIONAL_EXCEEDED"
    PORTFOLIO_NOTIONAL_EXCEEDED = "PORTFOLIO_NOTIONAL_EXCEEDED"
    INSUFFICIENT_CAPITAL = "INSUFFICIENT_CAPITAL"
    DAILY_LOSS_LIMIT_REACHED = "DAILY_LOSS_LIMIT_REACHED"
    CORRELATED_RISK_EXCEEDED = "CORRELATED_RISK_EXCEEDED"
    INVALID_CONTRACT = "INVALID_CONTRACT"
    LOT_SIZE_UNAVAILABLE = "LOT_SIZE_UNAVAILABLE"
    INVALID_LOT_SIZE = "INVALID_LOT_SIZE"
    POSITION_SIZE_TOO_SMALL = "POSITION_SIZE_TOO_SMALL"
    DUPLICATE_RISK_RESERVATION = "DUPLICATE_RISK_RESERVATION"
    MISSING_REQUIRED_INPUT = "MISSING_REQUIRED_INPUT"
    UNKNOWN_RISK_STATE = "UNKNOWN_RISK_STATE"


class TradeSide(StrEnum):
    """Direction of a proposed trade."""

    LONG = "LONG"
    SHORT = "SHORT"
