"""
Unit tests for OBS21: Real Runtime Integration.

Exercises the actual AlphaForge runtime flow using real application paths and deterministic
test doubles:
DATA -> SIGNAL -> RISK -> SECURITY -> ORDER SUBMISSION -> FSM -> RECONCILIATION

Invariants:
- Events must be automatically generated by invoking actual domain methods.
- The test must NOT manually call dispatcher.emit().
"""

from __future__ import annotations

import json
from datetime import datetime
from decimal import Decimal
from pathlib import Path
from typing import Any, cast

from alphaforge.broker.models import BrokerOrderRequest, BrokerOrderType
from alphaforge.broker.paper import PaperBroker
from alphaforge.data.normalization import MarketDataNormalizer
from alphaforge.data.store import CandleStore
from alphaforge.execution.enums import OrderSide, OrderState
from alphaforge.execution.idempotency import OrderRole
from alphaforge.execution.state_machine import OrderStateMachine
from alphaforge.observability.hub import (
    OrderFSMObservabilityAdapter,
    ReconciliationObservabilityAdapter,
    reset_observability_hub,
    set_global_dispatcher,
)
from alphaforge.observability.sinks import InMemoryObservabilitySink, SafeObservabilityDispatcher
from alphaforge.reconciliation.gate import ReconciliationGate
from alphaforge.reconciliation.reconciler import ColdBootReconciler
from alphaforge.reconciliation.state_store import InMemoryStateStore
from alphaforge.risk.engine import evaluate_trade_risk
from alphaforge.risk.enums import RiskDecisionState, TradeSide
from alphaforge.risk.models import PortfolioRiskState, RiskConfig, RiskInput
from alphaforge.security.authorizer import SecureBroker, SecurityAuthorizer
from alphaforge.security.config import SecurityConfig
from alphaforge.security.credentials import CredentialStore
from alphaforge.security.kill_switch import KillSwitch
from alphaforge.security.startup import SecurityStartupGate
from alphaforge.strategy.config import StrategyConfig
from alphaforge.strategy.engine import DeterministicStrategyEngine

FIXTURES_DIR = Path(__file__).parent.parent.parent / "golden" / "fixtures"


def _load_scenario(name: str) -> dict[str, Any]:
    path = FIXTURES_DIR / name
    with path.open(encoding="utf-8") as f:
        return cast("dict[str, Any]", json.load(f))


def test_obs21_real_runtime_integration_flow() -> None:
    """
    OBS21: Mandatory real runtime integration test.
    Invokes actual AlphaForge domain paths and verifies automatic diagnostic emission.
    """
    reset_observability_hub()
    sink = InMemoryObservabilitySink()
    dispatcher = SafeObservabilityDispatcher([sink])
    set_global_dispatcher(dispatcher)

    try:
        # -------------------------------------------------------------
        # 1. REAL DATA NORMALIZATION PATH
        # -------------------------------------------------------------
        fixture = _load_scenario("scenario_01_valid_long.json")
        raw_exec: list[dict[str, Any]] = []
        for c in fixture["exec_candles"]:
            ts_str = c["timestamp"].replace("+00:00", "Z")
            raw_exec.append(
                {
                    "symbol": "NIFTY",
                    "instrument_type": "FUTURES",
                    "contract_id": "NIFTY26SEPFUT",
                    "exchange_timestamp": ts_str,
                    "received_timestamp": ts_str,
                    "timeframe": "3m",
                    "open": str(c["open"]),
                    "high": str(c["high"]),
                    "low": str(c["low"]),
                    "close": str(c["close"]),
                    "volume": int(c["volume"]),
                    "open_interest": c["open_interest"],
                    "source": "RAW_FEED",
                    "is_closed": bool(c["is_closed"]),
                }
            )

        normalizer = MarketDataNormalizer(default_timeframe="3m", min_required_candles=20)
        norm_result = normalizer.normalize_batch(raw_exec)
        assert norm_result.execution_allowed is True

        # Verify automatic DATA_RECEIVED event emission
        data_events = sink.get_by_type("DATA_RECEIVED")
        assert len(data_events) >= 1
        assert data_events[0].attributes["valid_count"] == len(norm_result.valid_candles)

        # Store candles for strategy evaluation
        store = CandleStore()
        store.add_candles(norm_result.valid_candles)

        # Normalize and store 15m confirmation candles
        raw_conf: list[dict[str, Any]] = []
        for c in fixture["conf_candles"]:
            ts_str = c["timestamp"].replace("+00:00", "Z")
            raw_conf.append(
                {
                    "symbol": "NIFTY",
                    "instrument_type": "INDEX",
                    "contract_id": "NIFTY-SPOT",
                    "exchange_timestamp": ts_str,
                    "received_timestamp": ts_str,
                    "timeframe": "15m",
                    "open": str(c["open"]),
                    "high": str(c["high"]),
                    "low": str(c["low"]),
                    "close": str(c["close"]),
                    "volume": int(c["volume"]),
                    "open_interest": c["open_interest"],
                    "source": "RAW_FEED",
                    "is_closed": bool(c["is_closed"]),
                }
            )
        normalizer_15m = MarketDataNormalizer(default_timeframe="15m")
        norm_result_15m = normalizer_15m.normalize_batch(raw_conf, timeframe="15m")
        store.add_candles(norm_result_15m.valid_candles)

        latest_3m = store.get_latest_candle("NIFTY", "3m")
        assert latest_3m is not None
        closed_count = len(fixture["exec_candles"]) - 1
        raw_exec_bridge = store.get_strategy_execution_input("NIFTY", "3m", count=closed_count)
        raw_conf_bridge = store.get_strategy_confirmation_input(
            "NIFTY", "15m", max_timestamp=latest_3m.exchange_timestamp
        )
        assert raw_exec_bridge is not None

        # -------------------------------------------------------------
        # 2. REAL STRATEGY EVALUATION PATH
        # -------------------------------------------------------------
        strat_cfg = StrategyConfig()
        strat_engine = DeterministicStrategyEngine(strat_cfg)
        eval_ts = datetime.fromisoformat(fixture["evaluation_timestamp"])

        from alphaforge.core.enums import FuturesConfirmationStatus

        signal = strat_engine.evaluate(
            raw_exec_candles=raw_exec_bridge,
            raw_conf_candles=raw_conf_bridge,
            futures_status=FuturesConfirmationStatus.CONFIRMED,
            evaluation_timestamp=eval_ts,
        )
        assert signal is not None

        # Verify automatic SIGNAL event emission
        strat_events = [e for e in sink.events if e.category == "STRATEGY"]
        assert len(strat_events) >= 1
        assert strat_events[-1].correlation_id == signal.signal_id

        # -------------------------------------------------------------
        # 3. REAL RISK EVALUATION PATH
        # -------------------------------------------------------------
        risk_input = RiskInput(
            signal_id=signal.signal_id.upper(),
            symbol="NIFTY",
            side=TradeSide.LONG,
            entry_price=Decimal("24500.00"),
            stop_price=Decimal("24400.00"),
            contract_id="NIFTY26SEPFUT",
            lot_size=50,
            contract_multiplier=Decimal("1"),
            account_equity=Decimal("10000000.00"),
            available_capital=Decimal("10000000.00"),
            proposed_quantity=50,
            evaluation_timestamp=eval_ts,
        )
        port_state = PortfolioRiskState(
            account_equity=Decimal("10000000.00"),
            available_capital=Decimal("10000000.00"),
            daily_starting_equity=Decimal("10000000.00"),
            current_equity=Decimal("10000000.00"),
        )
        risk_cfg = RiskConfig()
        risk_decision = evaluate_trade_risk(risk_input, port_state, risk_cfg)
        assert risk_decision.decision == RiskDecisionState.APPROVED

        # Verify automatic RISK event emission
        risk_events = sink.get_by_type("RISK_ACCEPTED")
        assert len(risk_events) >= 1
        assert risk_events[-1].correlation_id == signal.signal_id.upper()
        assert risk_events[-1].attributes["decision"] == "APPROVED"

        # -------------------------------------------------------------
        # 4. REAL SECURITY AUTHORIZER & SECURE BROKER PATH
        # -------------------------------------------------------------
        sec_cfg = SecurityConfig()
        ks = KillSwitch()
        recon_gate = ReconciliationGate(initially_open=True)
        startup_gate = SecurityStartupGate(
            security_config=sec_cfg,
            credential_store=CredentialStore(),
            kill_switch=ks,
            reconciliation_gate=recon_gate,
        )
        startup_gate.verify_startup()

        authorizer = SecurityAuthorizer(
            security_config=sec_cfg,
            kill_switch=ks,
            reconciliation_gate=recon_gate,
            startup_gate=startup_gate,
        )
        paper_broker = PaperBroker()
        secure_broker = SecureBroker(paper_broker, authorizer)

        req = BrokerOrderRequest(
            client_order_id="ORD-OBS21-101",
            symbol="NIFTY",
            side=OrderSide.BUY,
            quantity=50,
            order_type=BrokerOrderType.MARKET,
            role=OrderRole.ENTRY,
        )
        broker_order = secure_broker.submit_order(req)
        assert broker_order is not None

        # Verify automatic ORDER_SUBMIT and ORDER_ACK events
        sub_events = sink.get_by_type("ORDER_SUBMIT")
        ack_events = sink.get_by_type("ORDER_ACK")
        assert len(sub_events) >= 1
        assert sub_events[-1].client_order_id == "ORD-OBS21-101"
        assert len(ack_events) >= 1
        assert ack_events[-1].client_order_id == "ORD-OBS21-101"
        assert ack_events[-1].broker_order_id == broker_order.broker_order_id

        # -------------------------------------------------------------
        # 5. REAL EXECUTION FSM WITH OBSERVABILITY ADAPTER
        # -------------------------------------------------------------
        fsm_adapter = OrderFSMObservabilityAdapter(dispatcher)
        fsm = OrderStateMachine(
            order_id="ORD-OBS21-101",
            symbol="NIFTY",
            side=TradeSide.LONG,
            quantity=50,
            signal_id=signal.signal_id.upper(),
            transition_listener=fsm_adapter,
        )
        fsm.transition(OrderState.VALIDATED)
        fsm.transition(OrderState.SUBMITTED)
        fsm.transition(OrderState.ACKNOWLEDGED)
        fsm.transition(OrderState.FILLED, fill_qty=50, fill_price=Decimal("24500.00"))

        fills = sink.get_by_type("FILL_RECEIVED")
        assert len(fills) >= 1
        assert fills[-1].client_order_id == "ORD-OBS21-101"

        # -------------------------------------------------------------
        # 6. REAL RECONCILER WITH OBSERVABILITY ADAPTER
        # -------------------------------------------------------------
        recon_adapter = ReconciliationObservabilityAdapter(dispatcher)
        state_store = InMemoryStateStore()
        reconciler = ColdBootReconciler(
            broker=paper_broker,
            state_store=state_store,
            gate=recon_gate,
            reconciliation_listener=recon_adapter,
            on_start_listener=recon_adapter.on_start,
        )
        recon_result = reconciler.reconcile()
        assert recon_result is not None

        recon_starts = sink.get_by_type("RECONCILIATION_START")
        recon_outcomes = sink.get_by_type("RECONCILIATION_SUCCESS") + sink.get_by_type(
            "RECONCILIATION_MISMATCH"
        )
        assert len(recon_starts) >= 1
        assert len(recon_outcomes) >= 1
        assert recon_outcomes[0].correlation_id == recon_result.reconciliation_id
        assert recon_outcomes[0].attributes["status"] == recon_result.status.value

    finally:
        reset_observability_hub()
