"""
AlphaForge Upstox Real-Market Shadow Data Adapter (Phase 17C).

READ-ONLY market data adapter for Upstox WebSocket v3 feed.

SAFETY INVARIANTS:
- ZERO order placement, modification, or cancellation API calls.
- ZERO live broker execution capability.
- ZERO order-routing imports or methods.
- Upstox is DATA ONLY — this adapter connects to the market-data feed WebSocket
  exclusively for consuming real-time tick/OHLC data in shadow mode.

PROVENANCE DISTINCTION:
- Provider authentication: validated Upstox access token, authorized WebSocket URI.
- Raw payload integrity: SHA-256 of exact received wire bytes.
- AlphaForge internal attestation: HMAC-SHA256 generated by AlphaForge over the
  captured event/provenance record. This is NOT an Upstox signature, NOT a provider
  signature. Upstox does not supply per-payload HMAC signatures.
"""

from __future__ import annotations

import asyncio
import contextlib
import hashlib
import json
import logging
import os
import queue
import ssl
import threading
import uuid
from datetime import UTC, datetime, timedelta, timezone
from decimal import Decimal
from enum import StrEnum
from pathlib import Path
from typing import TYPE_CHECKING, Any

from alphaforge.contract.enums import ContractStatus
from alphaforge.core.exceptions import DataIntegrityError
from alphaforge.data.enums import InstrumentType
from alphaforge.shadow_validation.enums import DataSourceType, MarketDataAnomalyType
from alphaforge.shadow_validation.market_data_adapter import (
    AbstractMarketDataStreamAdapter,
    ProvenanceVerifier,
)
from alphaforge.shadow_validation.models import FeedProvenanceToken, MarketStreamEvent
from alphaforge.shadow_validation.reconnect import (
    DisconnectReason,
    ReconnectPolicy,
    ReconnectStateMachine,
)

if TYPE_CHECKING:
    from collections.abc import AsyncIterator, Iterator

    from alphaforge.contract.models import ContractMaster

logger = logging.getLogger(__name__)

# --- Queue and Stream Policies ---


class QueueOverflowPolicy(StrEnum):
    """Policy governing bounded event queue overflow during message bursts."""

    FAIL_CLOSED = "FAIL_CLOSED"
    BACKPRESSURE = "BACKPRESSURE"


# --- Constants ---
UPSTOX_PROVIDER_NAME = "UPSTOX"
UPSTOX_AUTH_ENDPOINT = "https://api.upstox.com/v3/feed/market-data-feed/authorize"
UPSTOX_ACCESS_TOKEN_ENV = "UPSTOX_ACCESS_TOKEN"  # noqa: S105
UPSTOX_INSTRUMENT_KEY_ENV = "UPSTOX_INSTRUMENT_KEY"

# Canonical NIFTY Futures instrument key mapping for Upstox API v2/v3
UPSTOX_KNOWN_INSTRUMENT_KEYS: dict[str, str] = {
    "NIFTY26SEPFUT": "NSE_FO|68407",
    "NIFTY26OCTFUT": "NSE_FO|48704",
    "NIFTY26NOVFUT": "NSE_FO|61471",
}

# NSE/NFO session boundaries in UTC (IST 09:15-15:30 = UTC 03:45-10:00)
NSE_SESSION_START_UTC = datetime.min.replace(hour=3, minute=45, tzinfo=UTC).time()
NSE_SESSION_END_UTC = datetime.min.replace(hour=10, minute=0, tzinfo=UTC).time()

# IST offset for timestamp conversion
IST = timezone(timedelta(hours=5, minutes=30))

# Reconnection parameters
MAX_RECONNECT_ATTEMPTS = 5
RECONNECT_BASE_DELAY_SECONDS = 2.0
RECONNECT_MAX_DELAY_SECONDS = 60.0


class UpstoxConnectionError(ConnectionError):
    """Raised when Upstox connection cannot be established or is lost irrecoverably."""


class UpstoxAuthenticationError(UpstoxConnectionError):
    """Raised when Upstox authentication fails (missing/invalid token)."""


class _CandleAggregator:
    """
    Non-lookahead 1-minute closed candle aggregator.

    Aggregates ticks into 1-minute bars. A candle is closed ONLY after the
    minute interval has completed (i.e., a tick with a timestamp in the NEXT
    minute is received). No future tick is used for the current bar.
    """

    def __init__(self) -> None:
        self._current_minute: int | None = None
        self._open: float = 0.0
        self._high: float = 0.0
        self._low: float = 0.0
        self._close: float = 0.0
        self._volume: int = 0
        self._minute_start_ts: datetime | None = None
        self._tick_count: int = 0

    def add_tick(self, price: float, quantity: int, exchange_ts: datetime) -> dict[str, Any] | None:
        """
        Add a tick and return a closed candle dict if the previous minute completed.

        Returns None if no candle was closed yet.
        """
        tick_minute = exchange_ts.minute + exchange_ts.hour * 60

        if self._current_minute is None:
            # First tick
            self._start_new_bar(price, quantity, exchange_ts, tick_minute)
            return None

        if tick_minute != self._current_minute:
            # Minute boundary crossed — close the previous bar
            closed_candle = {
                "open": self._open,
                "high": self._high,
                "low": self._low,
                "close": self._close,
                "volume": self._volume,
                "minute_start_ts": self._minute_start_ts,
                "tick_count": self._tick_count,
            }
            # Start new bar with current tick
            self._start_new_bar(price, quantity, exchange_ts, tick_minute)
            return closed_candle

        # Same minute — update running bar
        self._high = max(self._high, price)
        self._low = min(self._low, price)
        self._close = price
        self._volume += quantity
        self._tick_count += 1
        return None

    def _start_new_bar(self, price: float, quantity: int, ts: datetime, minute_key: int) -> None:
        self._current_minute = minute_key
        self._open = price
        self._high = price
        self._low = price
        self._close = price
        self._volume = quantity
        self._minute_start_ts = ts.replace(second=0, microsecond=0)
        self._tick_count = 1


class UpstoxMarketDataAdapter(AbstractMarketDataStreamAdapter):
    """
    Read-only Upstox WebSocket v3 market data adapter for shadow validation.

    SAFETY: This class contains ZERO order-routing methods.
    It does NOT import, reference, or expose any order placement, modification,
    or cancellation API. It is strictly a market-data consumer.

    PROVENANCE: Every received payload generates an authentic FeedProvenanceToken
    with alpha_forge_attestation_hmac (INTERNAL AlphaForge attestation, NOT an
    Upstox signature). Raw wire bytes are captured and SHA-256 hashed.
    """

    def __init__(
        self,
        contract: ContractMaster,
        access_token: str | None = None,
        instrument_key: str | None = None,
        queue_size: int = 1000,
        overflow_policy: QueueOverflowPolicy = QueueOverflowPolicy.FAIL_CLOSED,
        reconnect_policy: ReconnectPolicy | None = None,
    ) -> None:
        super().__init__(contract=contract, provider_name=UPSTOX_PROVIDER_NAME)

        # --- Contract validation (fail-closed) ---
        self._validate_contract(contract)

        # --- Credentials (fail-closed if missing) ---
        self._access_token = access_token or os.environ.get(UPSTOX_ACCESS_TOKEN_ENV)
        self._instrument_key = instrument_key or os.environ.get(
            UPSTOX_INSTRUMENT_KEY_ENV,
            f"NSE_FO|{contract.contract_id}",
        )

        # --- Connection and streaming state ---
        self._websocket_uri: str | None = None
        self._provider_authenticated: bool = False
        self._ws: Any = None  # websockets.WebSocketClientProtocol at runtime
        self._queue_size = queue_size
        self._overflow_policy = overflow_policy
        self._reconnect_policy = reconnect_policy or ReconnectPolicy(
            max_attempts=MAX_RECONNECT_ATTEMPTS,
            base_delay_seconds=RECONNECT_BASE_DELAY_SECONDS,
            max_delay_seconds=RECONNECT_MAX_DELAY_SECONDS,
        )
        self._reconnect_fsm = ReconnectStateMachine(policy=self._reconnect_policy)
        self._ingestion_sequence_no: int = 0

        # --- Telemetry ---
        self._connection_start_ts: datetime | None = None
        self._connection_established_ts: datetime | None = None
        self._subscription_start_ts: datetime | None = None
        self._first_event_ts: datetime | None = None
        self._disconnect_ts: datetime | None = None
        self._total_received_messages: int = 0
        self._total_valid_market_events: int = 0
        self._invalid_events: int = 0
        self._sequence_gaps: int = 0
        self._duplicate_events: int = 0
        self._out_of_order_events: int = 0
        self._heartbeat_count: int = 0
        self._last_sequence_no: int = 0
        self._seen_event_hashes: set[str] = set()

        # --- Candle aggregation & streaming control ---
        self._candle_aggregator = _CandleAggregator()
        self._stream_stop_event: threading.Event | None = None

    @staticmethod
    def _validate_contract(contract: ContractMaster) -> None:
        """Fail-closed contract validation for Upstox NIFTY Futures shadow feed."""
        errors: list[str] = []

        if contract.exchange != "NSE":
            errors.append(f"exchange must be 'NSE', got '{contract.exchange}'")

        if contract.segment not in ("NFO", "NSE_FO"):
            errors.append(f"segment must be 'NFO' or 'NSE_FO', got '{contract.segment}'")

        if contract.underlying_symbol != "NIFTY":
            errors.append(f"underlying_symbol must be 'NIFTY', got '{contract.underlying_symbol}'")

        if contract.instrument_type != InstrumentType.FUTURES:
            errors.append(f"instrument_type must be FUTURES, got '{contract.instrument_type}'")

        if contract.status != ContractStatus.ACTIVE:
            errors.append(f"contract status must be ACTIVE, got '{contract.status}'")

        if contract.lot_size <= 0:
            errors.append(f"lot_size must be > 0, got {contract.lot_size}")

        if contract.tick_size <= Decimal("0"):
            errors.append(f"tick_size must be > 0, got {contract.tick_size}")

        now_utc = datetime.now(UTC)
        if contract.expiry_datetime <= now_utc:
            errors.append(
                f"contract expired at {contract.expiry_datetime.isoformat()}, "
                f"current time is {now_utc.isoformat()}"
            )

        if errors:
            msg = (
                f"UpstoxMarketDataAdapter: Contract validation FAILED for "
                f"'{contract.contract_id}'. Failing closed.\n"
                + "\n".join(f"  - {e}" for e in errors)
            )
            raise DataIntegrityError(msg)

    def connect(self) -> None:
        """
        Establish authenticated read-only WebSocket connection to Upstox market data feed.

        Fails closed if:
        - UPSTOX_ACCESS_TOKEN is missing or empty
        - Authorization endpoint returns error
        - WebSocket connection cannot be established
        """
        if not self._access_token:
            msg = (
                "UpstoxMarketDataAdapter: UPSTOX_ACCESS_TOKEN is missing. "
                "Cannot establish market data connection. Failing closed. "
                "Set UPSTOX_ACCESS_TOKEN environment variable."
            )
            raise UpstoxAuthenticationError(msg)

        self._connection_start_ts = datetime.now(UTC)

        try:
            # Step 1: Authorize via REST endpoint to get WebSocket URI
            self._websocket_uri = self._authorize_feed()
            self._provider_authenticated = True
            logger.info(
                "UpstoxMarketDataAdapter: Authorization successful. "
                "Provider authenticated. WebSocket URI obtained."
            )

            # Step 2: Establish WebSocket connection
            self._establish_websocket()
            self._connection_established_ts = datetime.now(UTC)
            self._is_connected = True
            self._session_id = (
                f"UPSTOX-LIVE-{uuid.uuid4().hex[:12]}-"
                f"{int(self._connection_established_ts.timestamp())}"
            )

            logger.info(
                "UpstoxMarketDataAdapter: WebSocket connected. "
                f"Session: {self._session_id}. "
                "Mode: READ-ONLY MARKET DATA / ZERO LIVE ORDERS"
            )

        except UpstoxAuthenticationError:
            self._provider_authenticated = False
            self._is_connected = False
            raise
        except Exception as exc:
            self._provider_authenticated = False
            self._is_connected = False
            msg = (
                f"UpstoxMarketDataAdapter: Connection failed — {exc}. "
                "Failing closed. No synthetic fallback. "
                "PHASE 17C BLOCKED — REAL MARKET DATA UNAVAILABLE."
            )
            raise UpstoxConnectionError(msg) from exc

    def _authorize_feed(self) -> str:
        """
        Call Upstox v3 feed authorization endpoint.

        Returns the authorized WebSocket redirect URI.
        Fails closed on any HTTP error.
        """
        import httpx  # noqa: PLC0415

        headers = {
            "Accept": "application/json",
            "Authorization": f"Bearer {self._access_token}",
        }

        try:
            response = httpx.get(
                UPSTOX_AUTH_ENDPOINT,
                headers=headers,
                timeout=10.0,
            )
        except Exception as exc:
            msg = (
                f"UpstoxMarketDataAdapter: HTTP request to authorization "
                f"endpoint failed — {exc}. Failing closed."
            )
            raise UpstoxConnectionError(msg) from exc

        if response.status_code == 401:  # noqa: PLR2004
            refreshed = self._attempt_auto_token_refresh()
            if refreshed:
                headers["Authorization"] = f"Bearer {self._access_token}"
                try:
                    response = httpx.get(
                        UPSTOX_AUTH_ENDPOINT,
                        headers=headers,
                        timeout=10.0,
                    )
                except Exception as exc:
                    msg = f"UpstoxMarketDataAdapter: Retry after token refresh failed — {exc}"
                    raise UpstoxConnectionError(msg) from exc

        if response.status_code == 401:  # noqa: PLR2004
            msg = (
                "UpstoxMarketDataAdapter: Authentication failed (HTTP 401). "
                "Access token is invalid or expired. Failing closed."
            )
            raise UpstoxAuthenticationError(msg)

        if response.status_code != 200:  # noqa: PLR2004
            msg = (
                f"UpstoxMarketDataAdapter: Authorization endpoint returned "
                f"HTTP {response.status_code}. Failing closed."
            )
            raise UpstoxConnectionError(msg)

        try:
            data = response.json()
            ws_uri = data["data"]["authorized_redirect_uri"]
        except (KeyError, TypeError, json.JSONDecodeError) as exc:
            msg = (
                "UpstoxMarketDataAdapter: Malformed authorization response. "
                f"Cannot extract WebSocket URI — {exc}. Failing closed."
            )
            raise UpstoxConnectionError(msg) from exc

        if not ws_uri or not ws_uri.startswith("wss://"):
            msg = (
                f"UpstoxMarketDataAdapter: Invalid WebSocket URI: '{ws_uri}'. "
                "Expected wss:// URI. Failing closed."
            )
            raise UpstoxConnectionError(msg)

        return str(ws_uri)

    def _attempt_auto_token_refresh(self) -> bool:
        """Attempt to automatically refresh expired Upstox token using TOTP credentials."""
        api_key = os.environ.get("UPSTOX_API_KEY", "")
        api_secret = os.environ.get("UPSTOX_API_SECRET", "")
        redirect_uri = os.environ.get("UPSTOX_REDIRECT_URI", "")
        mobile = os.environ.get("UPSTOX_MOBILE", "")
        pin = os.environ.get("UPSTOX_PIN", "")
        totp_key = os.environ.get("UPSTOX_TOTP_KEY", "")

        if not all([api_key, api_secret, redirect_uri, mobile, pin, totp_key]):
            return False

        try:
            logger.info("UpstoxMarketDataAdapter: Attempting automated OAuth token refresh with TOTP...")
            from alphaforge.shadow_validation.upstox_auth import UpstoxOAuthAuthenticator  # noqa: PLC0415
            auth = UpstoxOAuthAuthenticator(
                api_key=api_key,
                api_secret=api_secret,
                redirect_uri=redirect_uri,
                mobile=mobile,
                pin=pin,
                totp_key=totp_key,
            )
            res = auth.authenticate(max_retries=2)
            new_token = res["access_token"]
            self._access_token = new_token
            os.environ[UPSTOX_ACCESS_TOKEN_ENV] = new_token

            # Update .env file if it exists
            env_path = Path(".env")
            if env_path.exists():
                with contextlib.suppress(Exception):
                    from scripts.refresh_upstox_token import save_env_var  # noqa: PLC0415
                    save_env_var(env_path, UPSTOX_ACCESS_TOKEN_ENV, new_token)

            logger.info("UpstoxMarketDataAdapter: Automated token refresh succeeded.")
            return True
        except Exception as exc:
            logger.warning(f"UpstoxMarketDataAdapter: Automated token refresh failed: {exc}")
            return False

    def _establish_websocket(self) -> None:
        """Establish async WebSocket connection. Placeholder for actual async runtime."""
        # NOTE: Actual WebSocket connection is established in stream_events()
        # via asyncio. This method validates connectivity prerequisites.
        if not self._websocket_uri:
            msg = "UpstoxMarketDataAdapter: No WebSocket URI available. Failing closed."
            raise UpstoxConnectionError(msg)

    def disconnect(self) -> None:
        """Safely terminate WebSocket connection."""
        self._is_connected = False
        self._disconnect_ts = datetime.now(UTC)
        self._disconnect_count += 1
        self._ws = None
        if hasattr(self, "_stream_stop_event") and self._stream_stop_event is not None:
            self._stream_stop_event.set()
        logger.info(
            f"UpstoxMarketDataAdapter: Disconnected. Session: {self._session_id}. "
            f"Total market events: {self._total_valid_market_events}."
        )

    def _create_provenance_token(
        self,
        raw_payload: bytes,
        source_ts: datetime,
        provider_event_id: str | None = None,
    ) -> FeedProvenanceToken:
        """
        Create an authentic FeedProvenanceToken for a received Upstox payload.

        PROVENANCE DISTINCTION:
        - raw_payload_hash: SHA-256 of the exact received wire bytes from Upstox.
        - alpha_forge_attestation_hmac: INTERNAL AlphaForge HMAC-SHA256 attestation
          proving this event was captured through the verified adapter ingestion path.
          This is NOT an Upstox signature and NOT a provider-origin signature.
        - provider_event_id: Upstox does not supply per-message sequence IDs in the
          protobuf payload, so this is set to None unless explicitly available.
        """
        if not self._is_connected:
            msg = "UpstoxMarketDataAdapter: Cannot create provenance token while disconnected."
            raise DataIntegrityError(msg)

        raw_hash = hashlib.sha256(raw_payload).hexdigest()
        attestation_hmac = ProvenanceVerifier.generate_attestation_hmac(
            provider=UPSTOX_PROVIDER_NAME,
            session_id=self._session_id,
            raw_payload_hash=raw_hash,
        )

        return FeedProvenanceToken(
            provider=UPSTOX_PROVIDER_NAME,
            provider_authenticated=self._provider_authenticated,
            connection_session_id=self._session_id,
            source_timestamp=source_ts,
            provider_event_id=provider_event_id,
            raw_payload_hash=raw_hash,
            alpha_forge_attestation_hmac=attestation_hmac,
            is_live_external=True,
        )

    def _decode_protobuf_message(self, raw_bytes: bytes) -> dict[str, Any] | None:
        """
        Decode Upstox v3 protobuf binary message into a dict.

        Returns None if the message cannot be decoded (malformed payload).
        """
        try:
            from google.protobuf.json_format import MessageToDict  # noqa: PLC0415

            from alphaforge.shadow_validation import (  # noqa: PLC0415
                upstox_protobuf_pb2 as pb,
            )

            feed_response = pb.FeedResponse()  # type: ignore[attr-defined]
            feed_response.ParseFromString(raw_bytes)
            return MessageToDict(feed_response)
        except Exception:
            logger.warning(
                "UpstoxMarketDataAdapter: Failed to decode protobuf message. Flagging as INVALID.",
                exc_info=True,
            )
            self._invalid_events += 1
            return None

    def _extract_market_events_from_feed(
        self,
        decoded: dict[str, Any],
        raw_bytes: bytes,
        receive_ts: datetime,
    ) -> list[MarketStreamEvent]:
        """
        Extract normalized MarketStreamEvent(s) from a decoded FeedResponse.

        Handles both:
        - MarketOHLC bars (1-minute closed candles from provider)
        - LTPC ticks (aggregated into 1-minute bars by _CandleAggregator)

        Never fabricates timestamps, event IDs, or sequence numbers.
        """
        events: list[MarketStreamEvent] = []
        feeds = decoded.get("feeds", {})

        for instrument_key, feed_data in feeds.items():
            # Skip instruments that don't match our subscription
            if not self._is_target_instrument(instrument_key):
                continue

            full_feed = feed_data.get("fullFeed", {})
            market_ff = full_feed.get("marketFF", {})
            index_ff = full_feed.get("indexFF", {})
            ltpc_data = feed_data.get("ltpc") or market_ff.get("ltpc") or index_ff.get("ltpc")
            ohlc_list = market_ff.get("marketOHLC", {}).get("ohlc", []) or index_ff.get(
                "marketOHLC", {}
            ).get("ohlc", [])

            # --- Process OHLC bars (provider-supplied 1-minute candles) ---
            processed_1m_candle = False
            for ohlc in ohlc_list:
                interval = ohlc.get("interval", "")
                if interval != "1m":
                    continue  # Only process 1-minute bars

                try:
                    ts_ms = int(ohlc.get("ts", 0))
                    o_price = float(ohlc.get("open", 0.0))
                    h_price = float(ohlc.get("high", 0.0))
                    l_price = float(ohlc.get("low", 0.0))
                    c_price = float(ohlc.get("close", 0.0))
                    vol = int(float(ohlc.get("vol", 0)))
                except (ValueError, TypeError):
                    self._invalid_events += 1
                    continue

                if ts_ms <= 0:
                    self._invalid_events += 1
                    continue

                exchange_ts = datetime.fromtimestamp(ts_ms / 1000.0, tz=UTC)
                provenance = self._create_provenance_token(
                    raw_payload=raw_bytes,
                    source_ts=exchange_ts,
                    provider_event_id=None,  # Upstox does not supply per-OHLC event IDs
                )

                self._last_sequence_no += 1
                event = self._build_market_stream_event(
                    exchange_ts=exchange_ts,
                    receive_ts=receive_ts,
                    open_price=o_price,
                    high_price=h_price,
                    low_price=l_price,
                    close_price=c_price,
                    volume=vol,
                    provenance=provenance,
                )
                if event:
                    events.append(event)
                    processed_1m_candle = True

            # --- Process LTPC ticks (aggregate into 1-minute closed candles) ---
            # If no provider-supplied 1m bar arrived, aggregate incoming ticks via _CandleAggregator
            if ltpc_data and not processed_1m_candle:
                try:
                    ltp = float(ltpc_data.get("ltp", 0.0))
                    ltt_ms = int(ltpc_data.get("ltt", 0))
                    ltq = int(float(ltpc_data.get("ltq", 0)))
                except (ValueError, TypeError):
                    self._invalid_events += 1
                    continue

                if ltp <= 0 or ltt_ms <= 0:
                    self._invalid_events += 1
                    continue

                exchange_ts = datetime.fromtimestamp(ltt_ms / 1000.0, tz=UTC)
                closed_candle = self._candle_aggregator.add_tick(ltp, ltq, exchange_ts)

                if closed_candle:
                    candle_ts = closed_candle["minute_start_ts"]
                    provenance = self._create_provenance_token(
                        raw_payload=raw_bytes,
                        source_ts=candle_ts,
                        provider_event_id=None,
                    )
                    self._last_sequence_no += 1
                    event = self._build_market_stream_event(
                        exchange_ts=candle_ts,
                        receive_ts=receive_ts,
                        open_price=closed_candle["open"],
                        high_price=closed_candle["high"],
                        low_price=closed_candle["low"],
                        close_price=closed_candle["close"],
                        volume=closed_candle["volume"],
                        provenance=provenance,
                    )
                    if event:
                        events.append(event)

        return events

    def _build_market_stream_event(
        self,
        exchange_ts: datetime,
        receive_ts: datetime,
        open_price: float,
        high_price: float,
        low_price: float,
        close_price: float,
        volume: int,
        provenance: FeedProvenanceToken,
    ) -> MarketStreamEvent | None:
        """Build a validated MarketStreamEvent with anomaly detection."""
        anomalies: list[MarketDataAnomalyType] = []

        # Validate prices
        if any(p <= 0 for p in (open_price, high_price, low_price, close_price)):
            anomalies.append(MarketDataAnomalyType.INVALID)
            self._invalid_events += 1
            return None

        # Session boundary check
        event_time = exchange_ts.time()
        is_session = NSE_SESSION_START_UTC <= event_time <= NSE_SESSION_END_UTC

        # Duplicate detection via event hash
        event_hash = hashlib.sha256(
            f"{exchange_ts.isoformat()}-{close_price}-{volume}".encode()
        ).hexdigest()[:16]
        if event_hash in self._seen_event_hashes:
            anomalies.append(MarketDataAnomalyType.DUPLICATE)
            self._duplicate_events += 1
        self._seen_event_hashes.add(event_hash)

        # Out-of-order check
        if self._last_event_ts and exchange_ts < self._last_event_ts:
            anomalies.append(MarketDataAnomalyType.OUT_OF_ORDER)
            self._out_of_order_events += 1

        self._last_event_ts = exchange_ts
        self._total_valid_market_events += 1

        if self._first_event_ts is None:
            self._first_event_ts = exchange_ts

        processing_ts = datetime.now(UTC)
        self._last_sequence_no += 1
        self._ingestion_sequence_no = self._last_sequence_no

        event = MarketStreamEvent(
            event_id=f"UPSTOX-{self._session_id}-{self._last_sequence_no}",
            symbol=self._contract.underlying_symbol,
            contract_id=self._contract.contract_id,
            sequence_no=self._last_sequence_no,
            ingestion_sequence_no=self._ingestion_sequence_no,
            provider=UPSTOX_PROVIDER_NAME,
            instrument_key=self._instrument_key,
            raw_payload_hash=provenance.raw_payload_hash,
            exchange_timestamp=exchange_ts,
            ingestion_timestamp=receive_ts,
            processing_timestamp=processing_ts,
            open_price=Decimal(str(round(open_price, 2))),
            high_price=Decimal(str(round(high_price, 2))),
            low_price=Decimal(str(round(low_price, 2))),
            close_price=Decimal(str(round(close_price, 2))),
            volume=volume,
            data_source=DataSourceType.REAL_MARKET_SHADOW,
            anomalies=anomalies,
            is_session_valid=is_session,
            provenance=provenance,
        )
        self._reconnect_fsm.on_event_received(event)
        return event

    @property
    def subscription_instrument_key(self) -> str:
        """Resolve numeric Upstox instrument key for wire WebSocket subscription."""
        clean = self._instrument_key.replace("NSE_FO|", "")
        if clean in UPSTOX_KNOWN_INSTRUMENT_KEYS:
            return UPSTOX_KNOWN_INSTRUMENT_KEYS[clean]
        if self._instrument_key in UPSTOX_KNOWN_INSTRUMENT_KEYS:
            return UPSTOX_KNOWN_INSTRUMENT_KEYS[self._instrument_key]
        return self._instrument_key

    def _is_target_instrument(self, instrument_key: str) -> bool:
        """Check if the instrument key matches our configured subscription."""
        sub_key = self.subscription_instrument_key
        return (
            instrument_key == self._instrument_key
            or instrument_key == sub_key
            or instrument_key.endswith(f"|{self._contract.contract_id}")
            or instrument_key.endswith(f":{self._contract.contract_id}")
            or sub_key.endswith(f"|{instrument_key}")
            or instrument_key.endswith(sub_key)
            or (
                self._contract.underlying_symbol in instrument_key
                and ("FO" in instrument_key or "FUT" in instrument_key)
            )
        )

    @property
    def reconnect_fsm(self) -> ReconnectStateMachine:
        """Expose the reconnect and gap recovery state machine."""
        return self._reconnect_fsm

    async def stream_live_events(self) -> AsyncIterator[MarketStreamEvent]:
        """
        True real-time asynchronous market data streaming pipeline.

        Yields verified MarketStreamEvent immediately upon extraction and validation.
        Does NOT accumulate events in memory.
        """
        if not self._is_connected:
            msg = "UpstoxMarketDataAdapter: Not connected. Call connect() first. Failing closed."
            raise UpstoxConnectionError(msg)

        import websockets  # noqa: PLC0415

        ssl_context = ssl.create_default_context()

        try:
            async with websockets.connect(
                self._websocket_uri,  # type: ignore[arg-type]
                ssl=ssl_context,
            ) as ws:
                self._ws = ws
                logger.info("UpstoxMarketDataAdapter: WebSocket stream active (live pipeline).")

                # Subscribe to instrument using numeric wire key if available
                sub_key = self.subscription_instrument_key
                await asyncio.sleep(1)
                sub_msg = json.dumps(
                    {
                        "guid": f"alphaforge-{uuid.uuid4().hex[:8]}",
                        "method": "sub",
                        "data": {
                            "mode": "full",
                            "instrumentKeys": [sub_key],
                        },
                    }
                ).encode("utf-8")
                await ws.send(sub_msg)
                self._subscription_start_ts = datetime.now(UTC)
                logger.info(f"UpstoxMarketDataAdapter: Subscribed to {sub_key} (canonical: {self._instrument_key}).")

                async for message in ws:
                    receive_ts = datetime.now(UTC)
                    self._total_received_messages += 1
                    self._reconnect_fsm.on_message_received()

                    if isinstance(message, str):
                        raw_bytes = message.encode("utf-8")
                    else:
                        raw_bytes = bytes(message)

                    decoded = self._decode_protobuf_message(raw_bytes)
                    if decoded is None:
                        continue

                    msg_type = decoded.get("type", "")
                    if msg_type == "market_info":
                        self._heartbeat_count += 1
                        self._reconnect_fsm.on_heartbeat()
                        continue

                    events = self._extract_market_events_from_feed(decoded, raw_bytes, receive_ts)
                    for ev in events:
                        yield ev

        except websockets.ConnectionClosed as exc:
            logger.warning("UpstoxMarketDataAdapter: WebSocket connection closed by server.")
            self._reconnect_fsm.on_disconnect(
                DisconnectReason.SOCKET_DISCONNECT, details={"error": str(exc)}
            )
        except Exception as exc:
            logger.exception("UpstoxMarketDataAdapter: WebSocket stream error.")
            self._reconnect_fsm.on_disconnect(
                DisconnectReason.UNEXPECTED_TERMINATION, details={"error": str(exc)}
            )
            raise

    def stream_events(self) -> Iterator[MarketStreamEvent]:
        """
        True real-time synchronous streaming pipeline with bounded queue.

        Consumes events from the async stream in real time and yields them immediately
        to downstream consumers without full-session memory accumulation.

        Maintains bounded queue with explicit overflow behavior (FAIL_CLOSED / BACKPRESSURE).
        Never silently discards market events.
        """
        if not self._is_connected:
            msg = "UpstoxMarketDataAdapter: Not connected. Call connect() first. Failing closed."
            raise UpstoxConnectionError(msg)

        event_queue: queue.Queue[MarketStreamEvent | Exception | None] = queue.Queue(
            maxsize=self._queue_size
        )
        stop_event = threading.Event()

        def _worker() -> None:
            loop = asyncio.new_event_loop()
            asyncio.set_event_loop(loop)

            async def _consume() -> None:
                stream = self.stream_live_events()
                try:
                    async for event in stream:
                        if stop_event.is_set() or not self._is_connected:
                            break

                        if self._overflow_policy == QueueOverflowPolicy.FAIL_CLOSED:
                            try:
                                event_queue.put_nowait(event)
                            except queue.Full:
                                msg = (
                                    f"QUEUE_OVERFLOW: Ingestion queue capacity of "
                                    f"{self._queue_size} exceeded. Failing closed."
                                )
                                event_queue.put(DataIntegrityError(msg))
                                break
                        else:
                            # BACKPRESSURE
                            try:
                                event_queue.put(event, timeout=5.0)
                            except queue.Full:
                                msg = (
                                    f"QUEUE_BACKPRESSURE_TIMEOUT: Downstream consumer "
                                    f"blocked for >5.0s. Queue capacity {self._queue_size}. "
                                    f"Failing closed."
                                )
                                event_queue.put(DataIntegrityError(msg))
                                break
                except asyncio.CancelledError:
                    pass
                except Exception as exc:
                    event_queue.put(exc)
                finally:
                    try:
                        aclose = getattr(stream, "aclose", None)
                        if callable(aclose):
                            await aclose()
                    except Exception:  # noqa: S110
                        pass
                    event_queue.put(None)  # Sentinel to terminate generator

            async def _monitor_stop(consume_task: asyncio.Task[None]) -> None:
                while not stop_event.is_set() and self._is_connected:
                    await asyncio.sleep(0.05)
                if not consume_task.done():
                    consume_task.cancel()

            async def _main() -> None:
                consume_task = loop.create_task(_consume())
                monitor_task = loop.create_task(_monitor_stop(consume_task))
                with contextlib.suppress(asyncio.CancelledError):
                    await consume_task
                if not monitor_task.done():
                    monitor_task.cancel()
                    with contextlib.suppress(asyncio.CancelledError):
                        await monitor_task

            try:
                loop.run_until_complete(_main())
            finally:
                loop.close()

        worker_thread = threading.Thread(
            target=_worker,
            name="UpstoxLiveStreamWorker",
            daemon=True,
        )
        worker_thread.start()

        self._stream_stop_event = stop_event
        try:
            while self._is_connected and not stop_event.is_set():
                try:
                    item = event_queue.get(timeout=0.25)
                except queue.Empty:
                    continue
                if item is None:
                    break
                if isinstance(item, Exception):
                    raise item
                yield item
        finally:
            stop_event.set()
            self._stream_stop_event = None
            self.disconnect()
            worker_thread.join(timeout=2.0)

    def get_connection_telemetry(self) -> dict[str, Any]:
        """Comprehensive connection, data quality, and streaming telemetry."""
        base = super().get_connection_telemetry()
        base.update(
            {
                "provider": UPSTOX_PROVIDER_NAME,
                "provider_authenticated": self._provider_authenticated,
                "is_live_external": self._is_connected and self._provider_authenticated,
                "instrument_key": self._instrument_key,
                "ingestion_sequence_no": self._ingestion_sequence_no,
                "reconnect_state": self._reconnect_fsm.current_state.value,
                "reconnect_attempts": self._reconnect_fsm.attempt_count,
                "is_evaluation_allowed": self._reconnect_fsm.is_evaluation_allowed,
                "detected_gaps_count": len(self._reconnect_fsm.gaps),
                "queue_size": self._queue_size,
                "overflow_policy": self._overflow_policy.value,
                "connection_start": (
                    self._connection_start_ts.isoformat() if self._connection_start_ts else None
                ),
                "connection_established": (
                    self._connection_established_ts.isoformat()
                    if self._connection_established_ts
                    else None
                ),
                "subscription_start": (
                    self._subscription_start_ts.isoformat() if self._subscription_start_ts else None
                ),
                "first_market_event": (
                    self._first_event_ts.isoformat() if self._first_event_ts else None
                ),
                "last_market_event": (
                    self._last_event_ts.isoformat() if self._last_event_ts else None
                ),
                "disconnect_timestamp": (
                    self._disconnect_ts.isoformat() if self._disconnect_ts else None
                ),
                "total_received_messages": self._total_received_messages,
                "total_valid_market_events": self._total_valid_market_events,
                "invalid_events": self._invalid_events,
                "heartbeat_count": self._heartbeat_count,
                "sequence_gaps": self._sequence_gaps,
                "duplicate_events": self._duplicate_events,
                "out_of_order_events": self._out_of_order_events,
            }
        )
        return base

